# Generated by Django 2.2.6 on 2019-10-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191027_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-is_approved',)},
        ),
    ]
