# Generated by Django 2.2.6 on 2019-10-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191028_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('is_approved', '-creating_date')},
        ),
    ]
