# Generated by Django 2.2.6 on 2019-11-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191122_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderitems',
            field=models.ManyToManyField(related_name='order_items', to='shop.Cart'),
        ),
    ]
