# Generated by Django 2.2.6 on 2019-11-23 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ordered',
        ),
        migrations.CreateModel(
            name='SuccessfulPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Order')),
            ],
        ),
    ]
