# Generated by Django 2.2.6 on 2019-11-23 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20191123_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successfulpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
    ]
