# Generated by Django 2.2.6 on 2019-11-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20191123_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successfulpayment',
            name='orderitems',
        ),
        migrations.AddField(
            model_name='successfulpayment',
            name='orderitems',
            field=models.TextField(blank=True),
        ),
    ]
