# Generated by Django 2.2.6 on 2019-11-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20191123_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
                ('sub_category', models.ManyToManyField(related_name='_category_sub_category_+', to='shop.Category')),
            ],
        ),
    ]
