# Generated by Django 2.2.6 on 2019-11-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(blank=True, related_name='_category_sub_category_+', to='shop.Category'),
        ),
    ]
