# Generated by Django 2.2.6 on 2019-11-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_category_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
