# Generated by Django 2.2.6 on 2019-11-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20191127_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price1', models.IntegerField(blank=True, null=True)),
                ('price2', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
