# Generated by Django 2.2.6 on 2019-11-28 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20191127_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
